services:

  grafana:
    image: grafana/grafana:latest
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    volumes:
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./grafana/grc20-dashboard.json:/var/lib/grafana/dashboards/grc20.json
    ports:
      - "3000:3000"

volumes:
  tx-indexer-data: